/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.rmi.RemoteException;
import java.security.GeneralSecurityException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import server.IServer;
import server.User;

/**
 *
 * @author bertl
 */
public class CheckPassword extends javax.swing.JFrame {
    private String username;
    private String newPassword;
    private User user;
    private Chat chat;
    
    /**
     * Creates new form CheckPassword
     * @param username
     */
    public CheckPassword(String username, String newPassword, Chat chat) {
        this.username = username;
        this.user = null;
        this.newPassword = newPassword;
        this.chat = chat;
        initComponents();
        this.wrongLabel.setVisible(false);
        this.okLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        wrongLabel = new javax.swing.JLabel();
        okLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Checking your identity");

        jLabel1.setText("Please introduce your actual password");

        checkButton.setLabel("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        wrongLabel.setForeground(new java.awt.Color(255, 51, 51));
        wrongLabel.setText("Wrong password");

        okLabel.setForeground(new java.awt.Color(0, 153, 51));
        okLabel.setText("OK, logging you out to save changes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(wrongLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(okLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrongLabel)
                .addGap(18, 18, 18)
                .addComponent(okLabel)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        
        try {
            this.user = this.chat.getIface().login(this.username, this.passwordField.getText());
            if(user != null){
                this.wrongLabel.setVisible(false);
                this.okLabel.setVisible(true);
                
                //change pwd
                this.chat.getIface().changePassword(user, this.newPassword);
                    
                //For security reasons, we logout the client
                this.exitUser();
            } else {
                this.wrongLabel.setVisible(true);
            }
        } catch (RemoteException ex) {
            System.out.println("Wrong password");
        } catch (GeneralSecurityException ex) {
            Logger.getLogger(CheckPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkButtonActionPerformed
    
    /*
     * Logout of the user
     */
    private void exitUser() throws GeneralSecurityException {
        try {
            this.chat.getIface().deleteCallback(this.user, this.newPassword);
            JOptionPane.showMessageDialog(null, "Logging you out...", "Warning", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } catch (RemoteException ex) {
            Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel okLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel wrongLabel;
    // End of variables declaration//GEN-END:variables
}
